name: voyager_share
description: Shared code between Voyager and Horizon
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  xterm:
    git:
      url: https://github.com/Icyoung/xterm.dart.git
      ref: 7afd5c9
  shared_preferences: ^2.3.3
  cryptography: ^2.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

flutter:
  assets:
    - assets/pinyin_dict.json
    - assets/icons/square.grid.2x2.svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
