name: voyager_share
description: Shared code between Voyager and Horizon
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  xterm:
    path: ../../xterm
  shared_preferences: ^2.3.3
  cryptography: ^2.7.0
  google_fonts: ^6.2.1

flutter:
  assets:
    - assets/pinyin_dict.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
